### ISSUE TITLE
[Translation Bug] Everything suddenly revert back to Japanese

### ISSUE THREAD

**Issue by ethrundr** [KC3Kai/KC3Kai#949]
![screen shot 2015-10-13 at 15 30 04](https://cloud.githubusercontent.com/assets/13522800/10447435/51038536-71bf-11e5-8ddb-6142a3d8b5df.png)

As shown by the screenshot above, most of the ship names are changed back to Japanese, even though the Global setting was set to English:
![screen shot 2015-10-13 at 15 31 01](https://cloud.githubusercontent.com/assets/13522800/10447451/7583f7ce-71bf-11e5-81d0-e4b246d81be7.png)

Only newer ships after my latest sync and reload are displaying the proper transliteration, as what usually happened:
![screen shot 2015-10-13 at 15 33 53](https://cloud.githubusercontent.com/assets/13522800/10447512/e9486e1a-71bf-11e5-957f-34fc305e033e.png)

This also happens on the Admiral Panel, for ships that have their name reverted into Kanji in the Strategy Room's Shiplist:
![screen shot 2015-10-13 at 15 42 15](https://cloud.githubusercontent.com/assets/13522800/10447646/23a5a892-71c1-11e5-9206-8c5882ee48e3.png)

After reloading the extension several times, finally the Current Fleet list are "attacked" as well:
![screen shot 2015-10-13 at 15 53 41](https://cloud.githubusercontent.com/assets/13522800/10447807/ab7120de-71c2-11e5-81b6-597e008b6ef0.png)

Latest build was:
- KC3kai on 90a415e
- kc3-translations on 3b8d310

Update: I was try to re-sync and re-load everything, and the problem persist. I suppose there is something doesn't right, either with my extension settings or with the translation codes.

**Comment by ReiFan49** [comment]
16cf176731592c1c61560ff6659d595bb6be7e9c
wait...

**Comment by dragonjet** [comment]
tbh I can't make an effective fix, I don't recognize the code anymore :sweat_smile:

and I thought that would be the case, there another commit after that though that `this.cache[..` is returned within the `if(typeof this._ship[bare] !== "undefined"){` clause

**Comment by ReiFan49** [comment]
i thought the comment is enough to tell what happens on the code that i've committed :sweat_smile:
it's like..

```
ReplacementTable (higher for earlier priority, one time use only)
Suffix Replacement
甲      A
改二    Kai Ni
改      Kai

JP Name: 翔鶴改二甲
Step Bare     Combo
0    翔鶴改二甲    /empty/
1    翔鶴改二     A
2    翔鶴       KaiNi, A
0123 01234567 01234
Result: this._ship[翔鶴] + Combo.join(" ")
```
![image](https://cloud.githubusercontent.com/assets/9847780/10485434/4a9c5826-72b4-11e5-85f4-bf9153252dc7.png)

**Comment by dragonjet** [comment]
does this still happen in the latest pulls though?

**Comment by ReiFan49** [comment]
sounds like nope '-')

**Comment by ethrundr** [comment]
Seems it has been fixed already...

**Comment by dragonjet** [comment]
but it doesn't seem there's a commit tagged in the issue, just curious @ReiFan49 what thing fixed this? XD i still don't get what happened :sweat_smile:

**Comment by ReiFan49** [comment]
https://github.com/KC3Kai/KC3Kai/commit/683af14f6078845fb2ef21cdc573f6b51f3fcf7c
_(:3

**Comment by dragonjet** [comment]
_(:3
